Axis Mutual Fund:
  data_dir: /Users/njp60/Documents/code/mutualfundbackend/funddata/data/Axis Mutual Fund
  output_file: /Users/njp60/Documents/code/AssetManagmentCompanyParser/output/axis_mutual_fund_portfolio.xlsx
  ISIN_file: /Users/njp60/Documents/code/AssetManagmentCompanyParser/ISIN/fundisin.xlsx
  amc_name: Axis Mutual Fund
  sheets_to_avoid: []
  column_mapping: {}
  final_columns:
  - Name of Instrument
  - ISIN
  - Coupon
  - Industry
  - Quantity
  - Market Value
  - '% to Net Assets'
  - Yield
  - Yield to call
  - Type
  - Scheme Name
  - AMC
HDFC Mutual Fund:
  data_dir: /Users/njp60/Documents/code/mutualfundbackend/funddata/data/HDFC Mutual Fund
  output_file: /Users/njp60/Documents/code/AssetManagmentCompanyParser/output/hdfc_mutual_fund_portfolio.xlsx
  ISIN_file: /Users/njp60/Documents/code/AssetManagmentCompanyParser/ISIN/fundisin.xlsx
  amc_name: HDFC Mutual Fund
  sheets_to_avoid: []
  column_mapping: {}
  final_columns:
  - Name of Instrument
  - ISIN
  - Coupon
  - Industry
  - Quantity
  - Market Value
  - '% to Net Assets'
  - Yield
  - Yield to call
  - Type
  - Scheme Name
  - AMC
ICICI Prudential Mutual Fund:
  data_dir: /Users/njp60/Documents/code/mutualfundbackend/funddata/data/ICICI Prudential Mutual Fund
  output_file: /Users/njp60/Documents/code/AssetManagmentCompanyParser/output/icici_prudential_mutual_fund_portfolio.xlsx
  ISIN_file: /Users/njp60/Documents/code/AssetManagmentCompanyParser/ISIN/fundisin.xlsx
  amc_name: ICICI Prudential Mutual Fund
  sheets_to_avoid: []
  column_mapping: {}
  final_columns:
  - Name of Instrument
  - ISIN
  - Coupon
  - Industry
  - Quantity
  - Market Value
  - '% to Net Assets'
  - Yield
  - Yield to call
  - Type
  - Scheme Name
  - AMC
kotak_mutual_fund:
  data_dir: /Users/njp60/Documents/code/mutualfundbackend/funddata/data/Kotak Mutual Fund
  output_file: /Users/njp60/Documents/code/AssetManagmentCompanyParser/output/kotak_mutual_fund_portfolio.xlsx
  amc_name: Kotak Mutual Fund
  sheets_to_avoid: []
  column_mapping: {}
  final_columns:
  - Name of Instrument
  - ISIN
  - Coupon
  - Industry
  - Quantity
  - Market Value
  - '% to Net Assets'
  - Yield
  - Yield to call
  - Type
  - Scheme Name
  - AMC
